### ISSUE TITLE
Example of yet-unnamed technique currently used on zachleat.com

### ISSUE THREAD

**Issue by TxHawks** [zachleat/web-font-loading-recipes#1]
Any chance you'd be willing to share the code of the technique you are currently using on your website? 

I do realize it's still an in-progress experiment.

**Comment by zachleat** [comment]
No docs yet but a demo is up on https://github.com/zachleat/web-font-loading-recipes/

> “The Compromise”: Critical FOFT with preload, with a polyfill fallback emulating font-display: optional

**Comment by TxHawks** [comment]
Thanks
