### ISSUE TITLE
Why use sessionStorage over localStorage

### ISSUE THREAD

**Issue by TxHawks** [zachleat/web-font-loading-recipes#2]
Is there a reason to use `sessionStorage` over `localStorage` to optimize for repeat visits? My understanding is that using `sessionStorage` only optimizes for repeat visits within the same window (so not even new tab), while `localStorage` could also for repeat visits after the window is closed or a new tab is opened.

Am I missing something?

**Comment by zachleat** [comment]
It’s mostly a personal preference based on cache invalidation assumptions. We’re using this flag as a loose approximation of having the font files in cache. It’s all in how you’d like it to fail, when it does.

* `sessionStorage` will request more often than it needs but is unlikely to fail with a false positive
* `localStorage` will request less often but is more likely to false positive (thinks it’s in cache when it isn’t)

**Comment by zachleat** [comment]
Of course this could be improved with serviceworker, too :+1:
