### ISSUE TITLE
Font loading strategy for my website?

### ISSUE THREAD

**Issue by IgnaciodeNuevo** [zachleat/web-font-loading-recipes#4]
Hey @zachleat, I'm redesigning my website. Can I ask you something? I have 2 fonts (each with its respective subset, latin only, A-Z, a-z, 0-9 and basic punctuation), one for headlines and another for body. What would be the technique you would recommend me to use to load fonts?

I've thought of using: Critical FOFT with Data URI or FOUT with a Class. What do you think? 🤔 I've reread your guide.

![fonts](https://user-images.githubusercontent.com/10051329/46934850-8b262600-d059-11e8-954a-e6a4e1dbe83e.jpg)

**Comment by zachleat** [comment]
Continued here: https://twitter.com/zachleat/status/1089959842373079040

Can we close this one @IgnaciodeNuevo?

**Comment by IgnaciodeNuevo** [comment]
Yep, thank you so much!
